#include <kernel/ports.h>
#include <kernel/pic.h>
#include <kernel/io.h>

void init_pic(void)
{
    outb(PORT_8259_PIC_MASTER_COMMAND,  PIC_ICW1_INIT + PIC_ICW1_ICW4);
    outb(PORT_8259_PIC_SLAVE_COMMAND,   PIC_ICW1_INIT + PIC_ICW1_ICW4);

    outb(PORT_8259_PIC_MASTER_DATA,     PIC_MASTER_START_OFFSET);
    outb(PORT_8259_PIC_SLAVE_DATA,      PIC_SLAVE_START_OFFSET);

    outb(PORT_8259_PIC_MASTER_DATA,     PIC_MASTER_PIN_CONNECTION_TO_SLAVE);
    outb(PORT_8259_PIC_SLAVE_DATA,      PIC_SLAVE_ID);

    outb(PORT_8259_PIC_MASTER_DATA,     PIC_ICW4_8086);
    outb(PORT_8259_PIC_SLAVE_DATA,      PIC_ICW4_8086);

    outb(PORT_8259_PIC_MASTER_DATA,     PIC_MASTER_INTERRUPT_MASK);
    outb(PORT_8259_PIC_SLAVE_DATA,      PIC_SLAVE_INTERRUPT_MASK);
}
